import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Headvideo from "../components/headvideo";
import Projects from "../components/Projects";
import Skills from "../components/skills";
import LanguagesLogos from "../components/languages-logos";
import EmblaCarousel from "../components/Carousel";
import { useContext } from "react";
import SizeObserver, { sizeContext } from "../utils/size-observer";
import Contact from "../components/contact";
const Home: NextPage = () => {
  let windowWidth = useContext(sizeContext);
  return (
    <div>
      <Head>
        <title>Degryse Mehdi Developpeur Web Front End </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headvideo />

      <Skills />
      <LanguagesLogos context={windowWidth} />
      <Projects />
      <Contact />
    </div>
  );
};

export default Home;
